;
; Agent pool configuration
;

[general]
; The general section of this config is not currently used, but reserved
; for future use.

;[agent-id]
; Define ackcall to require the agent to give a DTMF acknowledgement
; when the agent receives a call.
; The channel variable AGENTACKCALL overrides on agent login.
; Default is "no".
;ackcall=no
;
; Set what DTMF key sequence the agent should use to acknowledge a call.
; The channel variable AGENTACCEPTDTMF overrides on agent login.
; This option is ignored unless ackcall is enabled.
; Default is "#".
;acceptdtmf=##
;
; Set how many seconds a call for the agent has to wait for the agent to
; acknowledge the call before the agent is automatically logged off.  If
; set to zero then the call will wait forever for the agent to acknowledge.
; The channel variable AGENTAUTOLOGOFF overrides on agent login.
; This option is ignored unless ackcall is enabled.
; Default is 0.
;autologoff=15
;
; Set the minimum amount of time after disconnecting a call before
; the agent can receive a new call in milliseconds.
; The channel variable AGENTWRAPUPTIME overrides on agent login.
; Default is 0.
;wrapuptime=5000
;
; Set the musiconhold class for the agent.
; Default is "default".
;musiconhold=default
;
; Enable recording calls the agent takes automatically by invoking the
; DTMF automixmon feature when the agent connects to a caller.
; See features.conf.sample for information about the automixmon feature.
; Default is "no".
;recordagentcalls=yes
;
; The sound file played to alert the agent when a call is present.
; Default is "beep".
;custom_beep=beep
;
; A friendly name for the agent used in log messages.
; Default is "".
;fullname=Mark Spencer
;
; --------------------------------------------------
;
; This section contains example agent definitions:
;
; Define a template called my-agents:
;[my-agents](!)
;autologoff=15
;ackcall=yes
;acceptdtmf=##
;
; Define agent 1001 using the my-agents template:
;[1001](my-agents)
;fullname=Mark Spencer
;
; Define agent 1002 using the my-agents template:
;[1002](my-agents)
;fullname=Will Meadows

[88555] (my-agents)
fullname=SAHIL

[6657] (my-agents)
fullname=Android

[302] (my-agents)
fullname=Dheeraj Kankriyal

[303] (my-agents)
fullname=Sawan Rai

[304] (my-agents)
fullname=Rambali Kumar

[305] (my-agents)
fullname=Kuntal Banerjee

[308] (my-agents)
fullname=Reeta

[309] (my-agents)
fullname=Ishaant

[314] (my-agents)
fullname=Pancham Barali

[316] (my-agents)
fullname=Amir Shah

[318] (my-agents)
fullname=Ram Pravesh

[319] (my-agents)
fullname=Abhijit basist

[999] (my-agents)
fullname=lokesh_a

[322] (my-agents)
fullname=Pallav Panwar

[325] (my-agents)
fullname=Arjun Singh

[9999] (my-agents)
fullname=HA

[8855] (my-agents)
fullname=stest1

[326] (my-agents)
fullname=Shalini Verma

[328] (my-agents)
fullname=Avinash Shukla

[329] (my-agents)
fullname=Kamal Shaukat

[330] (my-agents)
fullname=Ankesh Vyas

[331] (my-agents)
fullname=Kaushal Saraf

[332] (my-agents)
fullname=Himanshu Arora

[333] (my-agents)
fullname=Shubham Dixit

[334] (my-agents)
fullname=Suhail Ahmad Bhat

[101] (my-agents)
fullname=existing1

[102] (my-agents)
fullname=existing2

[335] (my-agents)
fullname=Shweta

[7] (my-agents)
fullname=Bhupendra Singh

[336] (my-agents)
fullname=Mohit Trehan

[337] (my-agents)
fullname=Ngute Thele

[338] (my-agents)
fullname=Nilesh Seth

[339] (my-agents)
fullname=Kamal Shukla

[310] (my-agents)
fullname=Harmeet Kaur

[340] (my-agents)
fullname=Mohammad Tanjeem Hasan

[341] (my-agents)
fullname=Raju Verma 

[342] (my-agents)
fullname=Lokesh

[343] (my-agents)
fullname=Mamta Kumari
