[UWT-66.110.73.74]
context=from-trunk
host=66.110.73.74
type=peer
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[UWT-66.110.73.75]
context=from-trunk
host=66.110.73.75
type=peer
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[UWT-66.165.168.101]
context=from-trunk
host=66.165.168.101
type=peer
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[UWT-66.165.168.108]
context=from-trunk
host=66.165.168.108
type=peer
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[UWT-66.165.168.109]
context=from-trunk
host=66.165.168.109
type=peer
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[number-io-35.196.16.20]
context=from-trunk
host=35.196.16.20
type=peer
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[bluetone-in-216.120.186.67]
context=from-trunk
host=216.120.186.67
type=peer
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[bluetone-in-76.10.215.51]
context=from-trunk
host=76.10.215.51
type=peer
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[tata-out-202.54.112.194]
type=peer
qualify=yes
nat=force_rport,comedia
host=202.54.112.194
dtmfmode=rfc2833
disallow=all
context=from-internal
allow=ulaw
allow=alaw

[cheapvoip_outbound]
type=peer
qualify=yes
nat=force_rport,comedia
host=sip.cheapvoip.com
secret=Welcome@123
username=varunjolly
dtmfmode=rfc2833
disallow=all
context=from-trunk
allow=ulaw
allow=alaw


[peerless]
type=peer
qualify=yes
nat=force_rport,comedia
host=208.93.46.221
dtmfmode=rfc2833
context=from-trunk
disallow=all
allow=ulaw
allow=alaw

[peerless_outbound]
type=peer
qualify=yes
nat=force_rport,comedia
host=208.93.46.221
dtmfmode=rfc2833
context=from-trunk
disallow=all
allow=ulaw
allow=alaw

[madaan]
context=from-trunk
host=172.86.77.20
type=peer
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[lynktel-out-88.151.132.11]
context=from-trunk
host=88.151.132.11
type=friend
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[bcn-out]
type=peer
host=voip-f.evolveip.net
username=pu-0001033005-1
secret=Th!$iSUS4i7Su9907T
fromuser=pu-0001033005-1
fromdomain=voip-f.evolveip.net
defaultuser=pu-0001033005-1
authuser=pu-0001033005-1
insecure=invite,port
context=from-trunk
disallow=all
allow=ulaw
qualify=yes

[bluetone-out-173.231.47.102]
context=from-trunk
host=88.151.132.11
type=friend
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[lynktel-in-temp-34.71.229.90]
context=from-trunk
host=34.71.229.90
type=peer
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw

[madaan-2]
context=from-trunk
host=82.180.154.151
type=peer
qualify=yes
dtmfmode=rfc2833
nat=force_rport,comedia
disallow=all
allow=ulaw
allow=alaw
